source:      .
destination: ./_site
plugins:     ./_plugins
auto: true
exclude: [bin, CNAME, Gemfile, Gemfile.lock, README.md]
permalink: /:title
pygments: true
# markdown: rdiscount
markdown: redcarpet2
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
